version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14-browsers # Use an appropriate Node.js Docker image with browsers
    steps:
      - checkout
      - run:
          name: Update System and Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libnss3 libnspr4 libatk-bridge2.0-0 libatspi2.0-0 libgbm1 libxkbcommon0 libasound2
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
