version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14-browsers # Use an appropriate Node.js Docker image with browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
